---
development:
  cloud_name: dnwmckxn4
  api_key: '418167724192317'
  api_secret: avt-VlS2HQRPLJPFK7CF-WrdVSA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dnwmckxn4
  api_key: '418167724192317'
  api_secret: avt-VlS2HQRPLJPFK7CF-WrdVSA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dnwmckxn4
  api_key: '418167724192317'
  api_secret: avt-VlS2HQRPLJPFK7CF-WrdVSA
  enhance_image_tag: true
  static_file_support: false
